"""
Django settings for monCinema project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Render definit automatiquement RENDER=true sur tous ses services : on s'en
# sert pour distinguer la production du developpement local. En local, la cle
# par defaut suffit. En production, DJANGO_SECRET_KEY et DJANGO_DEBUG doivent
# etre definies explicitement, sinon le demarrage plante au lieu de se
# degrader silencieusement avec la cle de developpement (publiee sur GitHub).
IS_RENDER = os.environ.get("RENDER") == "true"
_secret_key = os.environ.get("DJANGO_SECRET_KEY")
_debug_raw = os.environ.get("DJANGO_DEBUG")

if IS_RENDER:
    if not _secret_key:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY doit etre definie en production (Render).")
    if _debug_raw is None:
        raise ImproperlyConfigured("DJANGO_DEBUG doit etre definie explicitement en production (Render).")
    SECRET_KEY = _secret_key
    DEBUG = _debug_raw == "True"
else:
    SECRET_KEY = _secret_key or "django-insecure-%kzuobtrag%_915%pv2m8nb54@t#qw1jz#w#15^l@e=jgtxgs5"
    DEBUG = (_debug_raw or "True") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cinema",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "monCinema.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "monCinema/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "monCinema.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr-ca"
TIME_ZONE = "America/Toronto"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "monCinema" / "static"]
# Destination de collectstatic en production. Inutilise en developpement.
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise: compresse les fichiers statiques et ajoute un hash au nom pour
# permettre une mise en cache longue duree. Inutilise en developpement.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    },
}


# Authentification
LOGIN_URL = "/login/"  # rediriger les non connectes
LOGIN_REDIRECT_URL = "/"  # rediriger apres une connexion reussie
LOGOUT_REDIRECT_URL = "/login/"  # rediriger apres une deconnexion
