# Generated by Django 6.0.1 on 2026-03-28 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('duree', models.PositiveIntegerField(default=120, help_text='Durée en minutes')),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('enfants', 'Enfants'), ('famille', 'Famille'), ('adultes', 'Adultes'), ('action', 'Action'), ('horreur', 'Horreur'), ('comedie', 'Comédie')], max_length=50)),
                ('img', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noSalle', models.CharField(max_length=50)),
                ('capacite', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
            ],
        ),
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTechno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateHeure', models.DateTimeField()),
                ('idFilm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.films')),
                ('idSalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dateAchat', models.DateTimeField(auto_now_add=True)),
                ('idRepresentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.representation')),
            ],
        ),
        migrations.CreateModel(
            name='TechFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFilm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.films')),
                ('idTechno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.technologie')),
            ],
            options={
                'unique_together': {('idFilm', 'idTechno')},
            },
        ),
        migrations.CreateModel(
            name='TechSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.salle')),
                ('idTechno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.technologie')),
            ],
            options={
                'unique_together': {('idSalle', 'idTechno')},
            },
        ),
    ]
