# Generated by Django 6.0.1 on 2026-03-28 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='techsalle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='techsalle',
            name='idSalle',
        ),
        migrations.RemoveField(
            model_name='techsalle',
            name='idTechno',
        ),
        migrations.AddField(
            model_name='films',
            name='technologies',
            field=models.ManyToManyField(to='cinema.technologie'),
        ),
        migrations.AddField(
            model_name='salle',
            name='technologies',
            field=models.ManyToManyField(to='cinema.technologie'),
        ),
        migrations.AlterField(
            model_name='films',
            name='categorie',
            field=models.CharField(choices=[('enfants', 'Enfants'), ('famille', 'Famille'), ('sci-fi', 'sci-fi'), ('action', 'Action'), ('horreur', 'Horreur'), ('comedie', 'Comédie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='salle',
            name='capacite',
            field=models.PositiveIntegerField(default=250, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.DeleteModel(
            name='TechFilm',
        ),
        migrations.DeleteModel(
            name='TechSalle',
        ),
    ]
