# Generated by Django 6.0.1 on 2026-03-28 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_techsalle_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='technologie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.technologie'),
        ),
    ]
