# Generated by Django 6.0.1 on 2026-03-29 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_representation_technologie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='categorie',
            field=models.CharField(choices=[('enfants', 'Enfants'), ('famille', 'Famille'), ('sci-fi', 'sci-fi'), ('action', 'Action'), ('horreur', 'Horreur'), ('comedie', 'Comédie'), ('adultes', 'Adultes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='representation',
            name='technologie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cinema.technologie'),
        ),
    ]
